# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
