# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_laboratorist_pharmacist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='address',
            field=models.CharField(blank=True, help_text='This is address', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='first_name',
            field=models.CharField(blank=True, help_text='This is First Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='last_name',
            field=models.CharField(blank=True, help_text='This is Last Name', max_length=100, null=True),
        ),
    ]
