# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='timestamp',
            new_name='admission',
        ),
        migrations.AddField(
            model_name='admission',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O', 'O Positive'), ('O', 'O Negetive)'), ('AB', 'AB Positive'), ('AB', 'AB Negetive'), ('A', 'A Positive'), ('A', 'A Negetive'), ('B', 'B Positive'), ('B', 'B Negetive')], max_length=1),
        ),
        migrations.AddField(
            model_name='admission',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='admission',
            name='description',
            field=models.CharField(blank=True, help_text='This is parient details', max_length=1000),
        ),
    ]
