# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20171011_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.AddField(
            model_name='admission',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
