# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20171011_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
