# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20171011_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='description',
            field=models.TextField(blank=True, help_text='This is parient details', max_length=1000),
        ),
    ]
