# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20171011_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
