# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0008_auto_20171011_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
