# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('private', models.BooleanField(default=True)),
                ('completed', models.BooleanField()),
                ('image1', models.FileField(blank=True, null=True, upload_to='medtests/%Y/%m/%d')),
                ('image2', models.FileField(blank=True, null=True, upload_to='medtests/%Y/%m/%d')),
                ('image3', models.FileField(blank=True, null=True, upload_to='medtests/%Y/%m/%d')),
                ('image4', models.FileField(blank=True, null=True, upload_to='medtests/%Y/%m/%d')),
                ('image5', models.FileField(blank=True, null=True, upload_to='medtests/%Y/%m/%d')),
            ],
        ),
    ]
