# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_hospital', '0003_blood_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('age', models.ImageField(blank=True, default=0, null=True, upload_to='')),
            ],
        ),
    ]
