# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(default='', max_length=50)),
                ('last_Name', models.CharField(default='', max_length=50)),
                ('user_name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_Contact_Number', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('department', models.CharField(blank=True, choices=[('N', 'Neurology'), ('E', 'ENT (Ear, Nose & Throat)'), ('C', 'Cardiovascular'), ('NE', 'Nephrology'), ('O', 'Orthopaediatrics')], max_length=1)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(default='', max_length=50)),
                ('last_Name', models.CharField(default='', max_length=50)),
                ('user_name', models.CharField(default='', max_length=30)),
                ('workplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital')),
            ],
        ),
        migrations.AddField(
            model_name='administrator',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital'),
        ),
    ]
