# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='emergencyContactNumber',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=None),
            preserve_default=False,
        ),
    ]
