# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20171011_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='emergencyContactName',
            new_name='emergency_Contact_Number',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='insurance',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='lastname',
        ),
    ]
